---
name: CICD pipeline for nodejs Application on EC2

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-nodejs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: npm install
      - run: npm run build-react
      - run: npm run  start-node

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /var/www/my-app/
          remote_host: ec2-54-162-199-140.compute-1.amazonaws.com
          remote_user: ubuntu
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"

...
